# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-instance.html

Description: This template deploys three EC2 instances in my environment - for web server, database server, and bastion host.

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String

  InstanceType:
    Description: EC2 instance type
    Type: String
  
  AMI:
    Description: AMI ID from custom image on the console for web server and database server
    Type: AWS::EC2::Image::Id

  BastionAMI:
    Description: AMI ID from custom image on the console for bastion host
    Type: AWS::EC2::Image::Id
    Default: ami-0bf0558a1b312d976

  KeyName:
    Description: EC2 Key Pair
    Type: AWS::EC2::KeyPair::KeyName

  DBServerSG:
    Description: Database Server Security Group
    Type: AWS::EC2::SecurityGroup::Id
    
  BastionSG:
    Description: Bastion Host Security Group
    Type: AWS::EC2::SecurityGroup::Id

  WebServerSG:
    Description: Web Server Security Group
    Type: AWS::EC2::SecurityGroup::Id
  
  VpcId:
    Description: VPC ID
    Type: AWS::EC2::VPC::Id
  
  PrivateSubnet1Id:
    Description: Private Subnet 1 ID
    Type: AWS::EC2::Subnet::Id

  PublicSubnet1Id:
    Description: Public Subnet 1 ID
    Type: AWS::EC2::Subnet::Id
  
  PublicSubnet2Id:
    Description: Public Subnet 2 ID
    Type: AWS::EC2::Subnet::Id

Resources:
  DBServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AMI
      VpcId: !Ref VpcId
      SecurityGroupIds:
        - !Ref DBServerSG
      SubnetId: !Ref PrivateSubnet1Id
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Database Server
  
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AMI
      SecurityGroupIds:
        - !Ref WebServerSG
      VpcId: !Ref VpcId
      SubnetId: !Ref PublicSubnet1Id
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Web Server

  BastionHostInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref BastionAMI
      KeyName: !Ref KeyName
      VpcId: !Ref VpcId
      SecurityGroupIds:
        - !Ref BastionSG
      SubnetId: !Ref PublicSubnet2Id
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Bastion Host

Outputs:
  WebServerInstance:
    Description: Web Server Instance
    Value: !Ref WebServerInstance

  DBServerInstance:
    Description: Database Server Instance
    Value: !Ref DBServerInstance

  BastionHostInstance:
    Description: Bastion Host Instance
    Value: !Ref BastionHostInstance