# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-instance.html

Description: This template deploys the DB instance for my environment.

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String

  InstanceType:
    Description: EC2 instance type
    Type: String

  DbServerAMI:
    Description: AMI ID from custom image on the console for database server
    Type: AWS::EC2::Image::Id

  KeyName:
    Description: EC2 Key Pair
    Type: AWS::EC2::KeyPair::KeyName

  DBServerSG:
    Description: Database Server Security Group
    Type: AWS::EC2::SecurityGroup::Id
  
  VpcId:
    Description: VPC ID
    Type: AWS::EC2::VPC::Id
  
  PrivateSubnet1Id:
    Description: Private Subnet 1 ID
    Type: AWS::EC2::Subnet::Id

Resources:
  DBServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref DbServerAMI
      KeyName: !Ref KeyName
      VpcId: !Ref VpcId
      SecurityGroupIds:
        - !Ref DBServerSG
      SubnetId: !Ref PrivateSubnet1Id
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Database Server

Outputs:
  DBServerInstanceId:
    Description: Database Server Instance
    Value: !Ref DBServerInstance