# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-targetgroup.html
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-listener.html

Description: This template sets up the target group, load balancer, and listener for my environment.

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String

  VpcId:
    Description: VPC ID
    Type: AWS::EC2::VPC::Id
  
  WebServerSG:
    Description: Web Server Security Group
    Type: AWS::EC2::SecurityGroup::Id
  
  PublicSubnet1Id:
    Description: Public Subnet 1 ID
    Type: AWS::EC2::Subnet::Id
  
  PublicSubnet2Id:
    Description: Public Subnet 2 ID
    Type: AWS::EC2::Subnet::Id
  
  PublicSubnet3Id:
    Description: Public Subnet 3 ID
    Type: AWS::EC2::Subnet::Id

Resources:
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VpcId
      TargetType: instance
      HealthCheckEnabled: True
      HealthCheckPath: /
      HealthCheckIntervalSeconds: 30
      HealthCheckPort: 3000
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 5
      UnhealthyThresholdCount: 2
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} TG

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: application
      Scheme: internet-facing
      SecurityGroups:
        - !Ref WebServerSG
      SubnetMappings:
        - SubnetId: !Ref PublicSubnet1Id
        - SubnetId: !Ref PublicSubnet2Id
        - SubnetId: !Ref PublicSubnet3Id
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} LB

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP

Outputs:
  TargetGroup:
    Description: Target Group ARN
    Value: !Ref TargetGroup

  LoadBalancer:
    Description: Load Balancer ARN
    Value: !Ref LoadBalancer

  Listener:
    Description: Listener ARN
    Value: !Ref Listener