# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ec2-instance.html

Description: This template creates a nested stack, allowing multiple templates to be deployed in a more modular way.

Parameters:
  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: devops2
  
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.nano
  
  KeyName:
    Description: EC2 Key Pair
    Type: AWS::EC2::KeyPair::KeyName
    Default: instance-key
  
  WebServerAMI:
    Description: AMI ID from custom image on the console for web server
    Type: AWS::EC2::Image::Id
    Default: ami-0406cef71d445a3a3

  BastionAMI:
    Description: AMI ID from custom image on the console for bastion host
    Type: AWS::EC2::Image::Id
    Default: ami-030128499f8d6f019

Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://cf-templates-1eco1r5bhxzo9-us-east-1.s3.amazonaws.com/vpc.yaml'
      Parameters:
        EnvironmentName: !Ref EnvironmentName

  SecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://cf-templates-1eco1r5bhxzo9-us-east-1.s3.amazonaws.com/security_groups.yaml'
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        EnvironmentName: !Ref EnvironmentName
  
  InstanceStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://cf-templates-1eco1r5bhxzo9-us-east-1.s3.amazonaws.com/instances.yaml'
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        InstanceType: !Ref InstanceType
        BastionAMI: !Ref BastionAMI
        BastionSG: !GetAtt SecurityGroupStack.Outputs.BastionSG
        PublicSubnet1Id: !GetAtt VPCStack.Outputs.PublicSubnet1Id
        KeyName: !Ref KeyName
        VpcId: !GetAtt VPCStack.Outputs.VpcId
  

  LoadBalancerStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://cf-templates-1eco1r5bhxzo9-us-east-1.s3.amazonaws.com/load_balancer.yaml'
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        EnvironmentName: !Ref EnvironmentName
        LoadBalancerSG: !GetAtt SecurityGroupStack.Outputs.LoadBalancerSG
        PublicSubnet1Id: !GetAtt VPCStack.Outputs.PublicSubnet1Id
        PublicSubnet2Id: !GetAtt VPCStack.Outputs.PublicSubnet2Id
        PublicSubnet3Id: !GetAtt VPCStack.Outputs.PublicSubnet3Id

  AutoScalingGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://cf-templates-1eco1r5bhxzo9-us-east-1.s3.amazonaws.com/autoscaling_group.yaml'
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.VpcId
        WebServerAMI: !Ref WebServerAMI
        WebServerSG: !GetAtt SecurityGroupStack.Outputs.WebServerSG
        EnvironmentName: !Ref EnvironmentName
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        PrivateSubnet1Id: !GetAtt VPCStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2Id: !GetAtt VPCStack.Outputs.PrivateSubnet2Id
        PrivateSubnet3Id: !GetAtt VPCStack.Outputs.PrivateSubnet3Id
        TargetGroup: !GetAtt LoadBalancerStack.Outputs.TargetGroup
    

